//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Region
    {
        public int RegionId { get; set; }
        public string Regionname { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tb_Status tb_Status { get; set; }
    }
}
