//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Data.Model_Generated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Branch()
        {
            this.tb_Employees = new HashSet<tb_Employees>();
            this.tb_Expenses = new HashSet<tb_Expenses>();
            this.tb_Income = new HashSet<tb_Income>();
            this.tb_Users = new HashSet<tb_Users>();
        }
    
        public int BranchId { get; set; }
        public string Branchname { get; set; }
        public string Branchcode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LGAId { get; set; }
        public string Address { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Coycode { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Createdby { get; set; }
    
        public virtual tb_Country tb_Country { get; set; }
        public virtual tb_LGA tb_LGA { get; set; }
        public virtual tb_State tb_State { get; set; }
        public virtual tb_Status tb_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Employees> tb_Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Expenses> tb_Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Income> tb_Income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Users> tb_Users { get; set; }
    }
}
