//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Data.Model_Generated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_City
    {
        public int CityId { get; set; }
        public string Cityname { get; set; }
        public Nullable<int> LGAId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual tb_Country tb_Country { get; set; }
        public virtual tb_LGA tb_LGA { get; set; }
        public virtual tb_State tb_State { get; set; }
    }
}
