//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Data.Model_Generated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employees
    {
        public int EmpId { get; set; }
        public string EmployeeNo { get; set; }
        public string SurName { get; set; }
        public string OtherNames { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StatOfOrigin { get; set; }
        public Nullable<int> LGAofOrigin { get; set; }
        public string ResidentialAddress { get; set; }
        public string Religion { get; set; }
        public string Genotype { get; set; }
        public string BloodGroup { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> ResumptionDate { get; set; }
        public string JobTitle { get; set; }
        public string GradeId { get; set; }
        public string Step { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string OfficialEmail { get; set; }
        public string OfficialPhone { get; set; }
    
        public virtual tb_Branch tb_Branch { get; set; }
        public virtual tb_Country tb_Country { get; set; }
        public virtual tb_Department tb_Department { get; set; }
        public virtual tb_Division tb_Division { get; set; }
    }
}
