//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Data.Model_Generated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Incoming_Fabrics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Incoming_Fabrics()
        {
            this.tb_Incoming_Fabric_Desc = new HashSet<tb_Incoming_Fabric_Desc>();
        }
    
        public int IncFabId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.DateTime> Date_Recorded { get; set; }
        public string Receipt_No { get; set; }
        public Nullable<int> Total_Amt { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Recorded_By { get; set; }
        public string Branch_Name { get; set; }
    
        public virtual tb_Branch tb_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Incoming_Fabric_Desc> tb_Incoming_Fabric_Desc { get; set; }
    }
}
