//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunSys.Data.Model_Generated
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Incoming_Fabric_Desc
    {
        public int IncFabDescId { get; set; }
        public Nullable<int> IncFabId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
    
        public virtual tb_Incoming_Fabrics tb_Incoming_Fabrics { get; set; }
    }
}
